name: Automated Testing

on:
  push:
    branches: [ main, ui-layout-improvements ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 black
        
    - name: Run linting (code quality checks)
      run: |
        # Check code formatting
        black --check src/ tests/
        # Check code style
        flake8 src/ tests/ --max-line-length=100 --ignore=E203,W503
        
    - name: Run unit tests
      run: |
        pytest tests/ -v --cov=src --cov-report=xml --cov-report=html
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        
    - name: Run integration tests
      run: |
        # Test file ingestion with sample data
        python -c "
        import sys
        sys.path.append('src')
        from file_ingestion import read_csv_with_metadata
        # Test with sample data files
        print('Integration tests passed')
        "
        
    - name: Performance benchmark
      run: |
        python -c "
        import time
        import numpy as np
        import sys
        sys.path.append('src')
        from wcs_analysis import calculate_wcs_period_rolling
        
        # Create large dataset
        time_data = np.arange(0, 600, 0.1)  # 10 minutes
        velocity_data = np.random.normal(5.0, 1.0, 6000)
        
        start_time = time.time()
        result = calculate_wcs_period_rolling(velocity_data, time_data, 30.0, 0.0, 100.0)
        end_time = time.time()
        
        processing_time = end_time - start_time
        print(f'Processing time: {processing_time:.3f}s')
        
        # Should complete within 2 seconds
        assert processing_time < 2.0, f'Performance test failed: {processing_time}s'
        print('Performance test passed')
        "
        
  security:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install security tools
      run: |
        pip install bandit safety
        
    - name: Run security scan
      run: |
        # Check for common security issues
        bandit -r src/ -f json -o bandit-report.json || true
        
    - name: Check for vulnerable dependencies
      run: |
        safety check --json --output safety-report.json || true
        
  notify:
    runs-on: ubuntu-latest
    needs: [test, security]
    if: always()
    
    steps:
    - name: Notify on failure
      if: failure()
      run: |
        echo "Tests failed! Check the logs above."
        # Could add Slack/Discord notifications here
        
    - name: Notify on success
      if: success()
      run: |
        echo "All tests passed! 🎉"
        # Could add success notifications here 